defaults:
  - data: fmow_multiscale
  - model: late_fusion_deit
  - optim: adamw_plateau
  - trainer: default
  - wandb: fmow
  - checkpoint: default
  - _self_

seed: 111

run_name: late-fusion-lightning-hydra-test

wandb:
  run_name: ${run_name}-${now:%y-%m-%d}

hydra:
  run:
    dir: log/hydra/${now:%Y-%m-%d}/${run_name}-${now:%H-%M-%S}
