slurm:
  partition: robolab
  cpus_per_task: 4   
  mem_per_cpu: 8GB

global_overrides:
  optim: adam_warmup_cosine
  data.preprocessed_dir: FMoW_LandSat_Norm

experiments:
  # ---------------- Backbone Models --------------------------------
  densenet_baseline:
    model: densenet_baseline

  efficientformer_baseline:
    model: efficientformer_baseline
  
  efficientnet_baseline:
    model: efficientnet_baseline
  
  deit_baseline:
    model: deit_baseline

  satclip_image_enc_baseline:
    model: satclip_image_enc_baseline
    
  satclip_le_enc_baseline:
    model: satclip_le_enc_baseline

  satclip_le_enc_baseline_no_domain:
    model: satclip_le_enc_baseline
    overrides:
      model.lr_domain_loss_coeff: 0.0

  satclip_le_enc_baseline_l_40:
    model: satclip_le_enc_baseline
    overrides:
      model.encoder.legendre_polys: 40

  satclip_le_enc_baseline_l_40_no_domain:
    model: satclip_le_enc_baseline
    overrides:
      model.encoder.legendre_polys: 40
      model.lr_domain_loss_coeff: 0.0

  dinov3_baseline:
    model: dinov3_baseline

  dinov3_lr_baseline:
    model: dinov3_lr_baseline
  
  dinov3_lr_baseline_no_domain:
    model: dinov3_lr_baseline
    overrides:
      model.lr_domain_loss_coeff: 0.0

  # ---------------- LR features only -------------------------------
  densenet_lr_baseline:
    model: densenet_lr_baseline

  densenet_lr_baseline_no_domain:
    model: densenet_lr_baseline
    overrides:
      model.lr_domain_loss_coeff: 0.0

  # ---------------- CoordDualBranch -------------------------------
  # Trained first with two linear layers, then with one linear only
  densenet_le_concat:
    model: densenet_le_concat

  densenet_le_film:
    model: densenet_le_film
  
  densenet_le_d3g:
    model: densenet_le_d3g

  densenet_le_geoprior:
    model: densenet_le_geoprior

  # ---------------- Dataset Normalization -------------------------
  # Normalized not with data statistics but with 0.5
  densenet_baseline_constnorm:
    model: densenet_baseline
    overrides:
      data.preprocessed_dir: FMoW_LandSat_ 
