slurm:
  partition: robolab
  cpus_per_task: 4
  mem_per_cpu: 8GB
  nodelist: gaia4,gaia5,gaia7

global_overrides:
  optim: adam_warmup_cosine
  data.source: preprocessed
  data.preprocessed_dir: FMoW_LandSat_Norm

experiments:
  # ---------------- Stacked Inputs -------------------------
  densenet_stacked:
    model: densenet_stacked

  densenet_stacked_no_domain:
    model: densenet_stacked
    overrides:
      model.lr_domain_loss_coeff: 0.0

  densenet_stacked_zero_init_no_domain:
    model: densenet_stacked
    overrides:
      model.lr_domain_loss_coeff: 0.0
      model.encoder.landsat_channel_init: zero

  densenet_stacked_zero_init:
    model: densenet_stacked
    overrides:
      model.encoder.landsat_channel_init: zero

  densenet_stacked_he_init_no_domain:
    model: densenet_stacked
    overrides:
      model.lr_domain_loss_coeff: 0.0
      model.encoder.landsat_channel_init: he
  
  dinov3_stacked:
    model: dinov3_stacked

  dinov3_stacked_no_domain:
    model: dinov3_stacked
    overrides:
      model.lr_domain_loss_coeff: 0.0

  dinov3_stacked_zero_init:
    model: dinov3_stacked
    overrides:
      model.encoder.landsat_channel_init: zero

  dinov3_stacked_zero_init_no_domain:
    model: dinov3_stacked
    overrides:
      model.lr_domain_loss_coeff: 0.0
      model.encoder.landsat_channel_init: zero

  # ---------------- Higher Learning Rate -------------------------
  densenet_stacked_hlr:
    model: densenet_stacked
    overrides:
      optim.optimizer.lr: 1e-3

  dinov3_stacked_hlr:
    model: dinov3_stacked
    overrides:
      optim.optimizer.lr: 1e-3
