slurm:
  partition: robolab
  cpus_per_task: 4
  mem_per_cpu: 8GB
  nodelist: gaia4,gaia5,gaia7

global_overrides:
  data.frac: 1.0
  trainer.max_epochs: 50
  optim: adam_warmup_cosine
  data.source: preprocessed
  data.preprocessed_dir: FMoW_LandSat_Norm
  data.leave_asia_out: true

experiments:
  densenet_lao:
    model: densenet_baseline

  film_lao:
    model: densenet_film

  film_om_gauss_pe_freq_lao:
    model: densenet_film
    overrides:
      spatial: om_gauss_pe_freq

  film_om_gauss_pe_freq_lr_crop_14_9km_lao:
    model: densenet_film
    overrides:
      spatial: om_gauss_pe_freq
      data.preprocessed_dir: FMoW_LandSat_FullRes
      data.lr_crop_km: 14.91

  d3g_detach_hr_lao:
    model: densenet_d3g
    overrides:
      model.detach_hr_for_consistency: true
