slurm:
  partition: robolab
  cpus_per_task: 4
  mem_per_cpu: 8GB

global_overrides:
  data.frac: 1.0
  trainer.max_epochs: 50
  optim: adam_warmup_cosine
  data.preprocessed_dir: FMoW_LandSat_Norm

experiments:
  # ---------------- Fusion variants ------------------------------------
  concat:
    model: densenet_concat
    overrides:
      trainer.branch_ablation: true

  film:
    model: densenet_film
    overrides:
      trainer.branch_ablation: true

  geoprior:
    model: densenet_geoprior
    overrides:
      trainer.branch_ablation: true

  d3g:
    model: densenet_d3g

  multsim:
    model: densenet_multsim
    overrides:
      trainer.branch_ablation: true

  # ---------------- Gradient ablation ---------------------------
  multsim_detach:
    model: densenet_multsim
    overrides:
      model.detach_lr_for_task: true
      trainer.branch_ablation: true
  
  multsim_no_domain:
    model: densenet_multsim
    overrides:
      model.lr_domain_loss_coeff: 0.0
      trainer.branch_ablation: true

  concat_detach:
    model: densenet_concat
    overrides:
      model.detach_lr_for_task: true
      trainer.branch_ablation: true

  d3g_detach_lr:
    model: densenet_d3g
    overrides:
      model.detach_lr_for_consistency: true

  d3g_detach_hr:
    model: densenet_d3g
    overrides:
      model.detach_hr_for_consistency: true

  d3g_detach_both:
    model: densenet_d3g
    overrides:
      model.detach_hr_for_consistency: true
      model.detach_lr_for_consistency: true

  d3g_detach_both_constnorm:
    model: densenet_d3g
    overrides:
      model.detach_hr_for_consistency: true
      model.detach_lr_for_consistency: true
      data.preprocessed_dir: FMoW_LandSat_

  film_detach:
    model: densenet_film
    overrides:
      model.detach_lr_for_task: true
      trainer.branch_ablation: true

  film_no_domain:
    model: densenet_film
    overrides:
      model.lr_domain_loss_coeff: 0.0
      trainer.branch_ablation: true

  concat_no_domain:
    model: densenet_concat
    overrides:
      model.lr_domain_loss_coeff: 0.0
      trainer.branch_ablation: true
          
  geoprior_no_domain:
    model: densenet_geoprior
    overrides:
      model.lr_domain_loss_coeff: 0.0
      trainer.branch_ablation: true

  # ---------------- ReLU ablation -----------------------------
  multsim_no_relu:
    model: densenet_multsim
    overrides:
      model.fusion.pre_fusion_relu: false
      trainer.branch_ablation: true

  film_relu:
    model: densenet_film
    overrides:
      model.fusion.pre_fusion_relu: true
      trainer.branch_ablation: true

  # ------------------ Label Smoothing ------------------
  multsim_ls_0_1:
    model: densenet_multsim
    overrides:
      trainer.label_smoothing: 0.1
      trainer.branch_ablation: true

  multsim_ls_0_1_constnorm:
    model: densenet_multsim
    overrides:
      trainer.label_smoothing: 0.1
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true

  # ------------------ Channel Init ------------------
  multsim_channel_init_he:
    model: densenet_multsim
    overrides:
      model.landsat_channel_init: "he"
      trainer.branch_ablation: true
    
  multsim_channel_init_zero:
    model: densenet_multsim
    overrides:
      model.landsat_channel_init: "zero"
      trainer.branch_ablation: true

  # ------------------ Dataset Normalization -----------------------
  # Not data specific normalization but with 0.5
  multsim_constnorm:
    model: densenet_multsim
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true
  
  concat_constnorm:
    model: densenet_concat
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true

  film_constnorm:
    model: densenet_film
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true

  # ------------------ Spatial Encoding -----------------------
  multsim_om_bin:
    model: densenet_multsim
    overrides:
      spatial: om_bin
      trainer.branch_ablation: true

  multsim_om_gauss:
    model: densenet_multsim
    overrides:
      spatial: om_gauss
      trainer.branch_ablation: true

  multsim_om_gauss_constnorm:
    model: densenet_multsim
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      spatial: om_gauss
      trainer.branch_ablation: true

  multsim_pe:
    model: densenet_multsim
    overrides:
      spatial: pe
      trainer.branch_ablation: true

  multsim_pe_freq:
    model: densenet_multsim
    overrides:
      spatial: pe_freq
      trainer.branch_ablation: true

  film_om_bin:
    model: densenet_film
    overrides:
      spatial: om_bin
      trainer.branch_ablation: true

  film_om_gauss:
    model: densenet_film
    overrides:
      spatial: om_gauss
      trainer.branch_ablation: true

  film_pe:
    model: densenet_film
    overrides:
      spatial: pe
      trainer.branch_ablation: true

  film_pe_freq:
    model: densenet_film
    overrides:
      spatial: pe_freq
      trainer.branch_ablation: true

  film_om_gauss_pe_freq:
    model: densenet_film
    overrides:
      spatial: om_gauss_pe_freq
      trainer.branch_ablation: true

  film_om_bin_pe_freq:
    model: densenet_film
    overrides:
      spatial: om_bin_pe_freq
      trainer.branch_ablation: true

  film_om_bin_pe:
    model: densenet_film
    overrides:
      spatial: om_bin_pe
      trainer.branch_ablation: true

  film_om_gauss_pe:
    model: densenet_film
    overrides:
      spatial: om_gauss_pe
      trainer.branch_ablation: true

  # ----------------- Alternate Freezing ----------------------
  multsim_alternate_branches:
    model: densenet_multsim
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true
      trainer.alternating_freeze: true
      trainer.alternating_freeze_period: 2

  multsim_alternate_om_gauss:
    model: densenet_multsim
    overrides:
      data.preprocessed_dir: FMoW_LandSat_
      trainer.branch_ablation: true
      trainer.alternating_freeze: true
      trainer.alternating_freeze_period: 2
      spatial: om_gauss

  film_alternate_branches:
    model: densenet_film
    overrides:
      trainer.branch_ablation: true
      trainer.alternating_freeze: true
      trainer.alternating_freeze_period: 2


