# @package _global_
model:
  landsat_in_channels: 6
  hr_image_net: true
  lr_image_net: true

  hr_encoder:
    _target_: models.components.branches.DenseNetBranch
    in_channels: 3
    image_net: ${model.hr_image_net}

  lr_encoder:
    _target_: models.components.branches.DenseNetBranch
    in_channels: ${model.landsat_in_channels}
    image_net: ${model.lr_image_net}

  branches:
    _target_: models.components.branches.DualBranch
    landsat_channels: ${model.landsat_in_channels}

  model:
    _target_: models.components.fusion_model.D3GModel

  domain_loss_coeff: 0.2
  learnable_relation_coeff: 0.8
  d3g_loss_coeff: 0.5
  pred_domain_for_d3g: true
  domain_optimizer_lr_factor: 0.1
  detach_lr_for_consistency: false
  detach_hr_for_consistency: false

run_name: train-densenet-d3g
data:
  batch_size: 80 
