# @package _global_
model:
  hr_pretrained: true

  hr_encoder:
    _target_: models.components.branches.DenseNetBranch
    in_channels: 3
    pretrained: ${model.hr_pretrained}

  lr_encoder:
    _target_: models.components.branches.SatCLIPLocationBranch
    embed_dim: 512
    legendre_polys: 10
    capacity: 512
    num_hidden_layers: 2

  branches:
    _target_: models.components.branches.CoordDualBranch

  fusion:
    _target_: models.components.fusion.FilmFusion
    hr_dim: 1024
    lr_dim: 512
    out_dim: 1024
    pre_fusion_relu: false

  model:
    _target_: models.components.fusion_models.FeatureFusionModel

  lr_domain_loss_coeff: 0.1667
  domain_optimizer_lr_factor: 0.1
  detach_lr_for_task: false

run_name: train-densenet-satclip-film
data:
  batch_size: 80
