landsat_in_channels: 6
hr_image_net: false
lr_image_net: false

hr_encoder:
  _target_: models.components.branches.DenseNetBranch
  in_channels: 3
  image_net: ${model.hr_image_net}

lr_encoder:
  _target_: models.components.branches.DenseNetBranch
  in_channels: ${model.landsat_in_channels}
  image_net: ${model.lr_image_net}

branches:
  _target_: models.components.branches.DualBranch
  landsat_channels: ${model.landsat_in_channels}

fusion:
  _target_: models.components.fusion.ConcatFusion
  hr_dim: 1024
  lr_dim: 1024
  out_dim: 1024

model:
  _target_: models.components.fusion_model.LateFusionModel

enable_domain_head: true
domain_loss_coeff: 0.2
domain_optimizer_lr_factor: 0.1
