# @package _global_
model:
  hr_encoder:
    _target_: models.components.branches.DINOv3Branch
    in_channels: 3
    pretrained: true
    model_size: base
    freeze: false 

  model:
    _target_: models.components.fusion_model.SingleBranchModel

run_name: train-dinov3-baseline
data:
  batch_size: 64 
  num_workers: 8
trainer:
  max_epochs: 10
optim:
  optimizer:
    lr: 1e-3

