# @package _global_
model:
  hr_encoder:
    _target_: models.components.branches.TimmBranch
    model_name: tf_efficientnetv2_b1
    in_channels: 3
    image_net: true

  model:
    _target_: models.components.fusion_model.SingleBranchModel

run_name: train-efficientnet-baseline
data:
  batch_size: 128
