num_labels: 62
landsat_in_channels: 6
hr_image_net: true
lr_image_net: true

hr_encoder:
  _target_: models.components.branches.DenseNetBranch
  in_channels: 3
  image_net: ${model.hr_image_net}

lr_encoder:
  _target_: models.components.branches.DenseNetBranch
  in_channels: ${model.landsat_in_channels}
  image_net: ${model.lr_image_net}

branches:
  _target_: models.components.branches.DualBranch
  landsat_channels: ${model.landsat_in_channels}

fusion:
  _target_: models.components.fusion.ConcatFusion
  hr_dim: 1024
  lr_dim: 1024
  out_dim: 1024

model:
  _target_: models.components.late_fusion_model.LateFusionModel

enable_domain_head: true
domain_loss_coeff: 0.2
domain_optimizer_lr_factor: 0.1
domain_optimizer_weight_decay: 0.0
domain_scheduler_gamma: 0.96
domain_scheduler_step_size: 1