num_labels: 62
landsat_in_channels: 6
hr_image_net: true
lr_image_net: true

hr_encoder:
  _target_: models.components.branches.DeitBranch
  in_channels: 3
  image_net: ${model.hr_image_net}

lr_encoder:
  _target_: models.components.branches.DeitBranch
  in_channels: ${model.landsat_in_channels}
  image_net: ${model.lr_image_net}

branches:
  _target_: models.components.branches.DualBranch
  landsat_channels: ${model.landsat_in_channels}

model:
  _target_: models.components.late_fusion_model.D3GModel

enable_domain_head: true
domain_loss_coeff: 0.2
d3g_loss_coeff: 0.5 
pred_domain_for_d3g: true
domain_optimizer_lr_factor: 0.1
domain_optimizer_weight_decay: 0.0
domain_scheduler_gamma: 0.96
domain_scheduler_step_size: 1
