# @package _global_
model:
  hr_encoder:
    _target_: models.components.branches.SatCLIPImageBranch
    in_channels: 3
    pretrained: true
    unfreeze_all: true
    unfreeze_first_block: true 
    unfreeze_head: true
    num_unfreeze_last: 11 

  model:
    _target_: models.components.fusion_models.SingleBranchModel

run_name: train-satclip-image-enc-baseline
data:
  batch_size: 128
