metric_directions:
  test/test-od-task-ece: min

summary_metrics:
  - test/test-od-worst-group-task-acc
  - test/test-od-lr-domain-acc
  - test/test-od-hr-domain-acc

primary_metrics:
  - test/test-od-task-acc
  - test/test-id-task-acc
  - test/test-od-worst-group-task-acc

groups:
  - name: Fusion Comparison
    runs:
      - baselines@densenet_baseline
      - baselines@densenet_satclip_loc
      - concat
      - film
      - geoprior
      - d3g
      - multsim
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc

  - name: Gradient Ablation
    runs:
      - multsim
      - multsim_detach
      - multsim_no_domain
      - concat
      - concat_detach
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc
  
  - name: ReLU Ablation
    runs:
      - multsim
      - multsim_no_relu
      - film
      - film_relu
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc

  - name: Label Smoothing
    runs:
      - multsim
      - multsim_ls_0_1  
      - multsim_ls_0_1_constnorm
  
  - name: Normalization Ablation
    runs:
      - baselines@densenet_baseline
      - baselines@densenet_baseline_constnorm
      - multsim
      - multsim_constnorm
      - concat
      - concat_constnorm