metric_directions:
  test/test-od-task-ece: min

summary_metrics:
  - test/test-od-worst-group-task-acc
  - test/test-od-lr-domain-acc
  - test/test-od-hr-domain-acc

primary_metrics:
  - test/test-id-task-acc
  - test/test-od-task-acc
  - test/test-od-worst-group-task-acc

groups:
  - name: Baselines
    runs:
      - baselines@densenet_baseline
      - baselines@deit_baseline
      - baselines@efficientnet_baseline
      - baselines@efficientformer_baseline

  - name: HR LR Encoder Comparison
    runs:
      - baselines@densenet_baseline
      - baselines@densenet_lr_baseline_no_domain

  - name: SatCLIP Fusion
    runs:
      - baselines@densenet_baseline
      - baselines@densenet_le_concat
      - baselines@densenet_le_film
      - baselines@densenet_le_d3g
      - baselines@densenet_le_geoprior
    additional_metrics:
      - test/test-od-lr-domain-acc

  - name: Fusion Comparison
    runs:
      - baselines@densenet_baseline
      - concat_no_domain
      - film_no_domain

  - name: Fusion Comparison with Domain
    runs:
      - baselines@densenet_baseline
      - concat
      - film
      - geoprior
      - d3g
    additional_metrics:
      - test/test-od-lr-domain-acc

  - name: Gradient Flow 
    runs:
      - film
      - film_detach
      - film_no_domain
  
  - name: ReLU Ablation
    runs:
      - film
      - film_relu
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc

  - name: Label Smoothing
    runs:
      - multsim
      - multsim_ls_0_1  
  
  - name: Normalization Ablation
    runs:
      - baselines@densenet_baseline
      - baselines@densenet_baseline_constnorm
      - multsim
      - multsim_constnorm
      - concat
      - concat_constnorm
      - d3g
      - d3g_detach_both_constnorm
      - multsim_om_gauss_constnorm
      - film
      - film_constnorm
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc

  - name: Spatial Encodings
    runs:
      - film
      - film_om_gauss
      - film_pe_freq
      - film_om_gauss_pe_freq
          
  - name: Spatial Encodings Full
    runs:
      - film
      - film_om_bin
      - film_om_gauss
      - film_pe
      - film_pe_freq
      - film_om_bin_pe_freq
      - film_om_gauss_pe_freq
      - film_om_bin_pe
      - film_om_gauss_pe

  - name: Alternating Branch Freezing
    runs:
      - multsim
      - multsim_alternate_branches
      - multsim_alternate_om_gauss
      - film
      - film_alternate_branches
    additional_metrics:
      - test/test-od-lr-ablated-worst-group-task-acc
      - test/test-od-hr-ablated-worst-group-task-acc
