models:
  densenet_baseline: "DenseNet-121"
  densenet_concat: "Concat"
  densenet_film: "FiLM"
  densenet_d3g: "D3G"
  densenet_geoprior: "GeoPrior"
  densenet_multsim: "MultSim"
  densenet_lr_baseline: "DenseNet-121 LR"
  deit_baseline: "DeiT-Tiny"
  efficientformer_baseline: "EfficientFormerV2-S1"
  efficientnet_baseline: "EffNetV2-B1"
  densenet_le_concat: "SatCLIP, Concat"
  densenet_le_film: "SatCLIP, FiLM"
  densenet_le_d3g: "SatCLIP, D3G"
  densenet_le_geoprior: "SatCLIP, GeoPrior"
  dinov3_film: "DINOv3 FiLM"
  dinov3_baseline: "DINOv3"
  satclip_le_enc_baseline: "SatCLIP"
  densenet_stacked: "Dense EF"
  dinov3_stacked: "Dino EF"

  # Decision Fusion
  densenet_decision_fusion: "DenseNet-121"
  dinov3_decision_fusion: "DINOv3"

metrics:
  test/test-id-task-acc:
    plain: "ID Acc."
    latex: "ID Acc."
  test/test-od-task-acc:
    plain: "OOD Acc."
    latex: "OOD Acc."
  test/test-od-worst-group-task-acc:
    plain: "OOD WRA"
    latex: "OOD WRA"
  test/test-od-worst-group-top5-task-acc:
    plain: "OOD Top-5 WRA"
    latex: "OOD Top-5 WRA"
  test/test-od-top5-task-acc:
    plain: "OOD Top-5 Acc."
    latex: "OOD Top-5 Acc."
  test/test-id-top5-task-acc:
    plain: "ID Top-5 Acc."
    latex: "ID Top-5 Acc."
  test/test-od-lr-domain-acc:
    plain: "OOD LR Domain Acc."
    latex: "OOD LR Domain Acc."
  test/test-od-hr-domain-acc:
    plain: "OOD HR Domain Acc."
    latex: "OOD HR Domain Acc."
  test/test-od-domain-acc:
    plain: "OOD Domain Acc."
    latex: "OOD Domain Acc."
  test/test-od-task-ece:
    plain: "OOD ECE"
    latex: "OOD ECE"
  test/test-id-task-ece:
    plain: "ID ECE"
    latex: "ID ECE"
  test/test-od-lr-ablated-worst-group-task-acc:
    plain: "OD Acc LR Constant"
    latex: "OD Acc LR Constant"
  test/test-od-hr-ablated-worst-group-task-acc:
    plain: "OD Acc HR Constant"
    latex: "OD Acc HR Constant"
  test/test-od-region-africa-task-acc:
    plain: "OOD Africa"
    latex: "OOD Africa"
  test/test-od-region-europe-task-acc:
    plain: "OOD Europe"
    latex: "OOD Europe"
  test/test-od-region-americas-task-acc:
    plain: "OOD Americas"
    latex: "OOD Americas"
  test/test-od-region-asia-task-acc:
    plain: "OOD Asia"
    latex: "OOD Asia"
  test/test-od-region-oceania-task-acc:
    plain: "OOD Oceania"
    latex: "OOD Oceania"
  test/test-id-region-africa-task-acc:
    plain: "ID Africa"
    latex: "ID Africa"
  test/test-id-region-europe-task-acc:
    plain: "ID Europe"
    latex: "ID Europe"
  test/test-id-region-americas-task-acc:
    plain: "ID Americas"
    latex: "ID Americas"
  test/test-id-region-asia-task-acc:
    plain: "ID Asia"
    latex: "ID Asia"
  test/test-id-region-oceania-task-acc:
    plain: "ID Oceania"
    latex: "ID Oceania"
  test/test-id-task-entropy-correct:
    plain: "ID H^+"
    latex: 'ID $\text{H}^+$'
  test/test-id-task-entropy-incorrect:
    plain: "ID H^-"
    latex: 'ID $\text{H}^-$'
  test/test-od-task-entropy-correct:
    plain: "OOD H^+"
    latex: 'OOD $\text{H}^+$'
  test/test-od-task-entropy-incorrect:
    plain: "OOD H^-"
    latex: 'OOD $\text{H}^-$'
  test/test-od-region-africa-class-airport-task-acc:
    plain: "OOD Airport"
    latex: 'OOD Airport'
  test/test-od-region-africa-class-runway-task-acc:
    plain: "OOD Runway"
    latex: 'OOD Runway'
  test/test-od-region-africa-class-place_of_worship-task-acc:
    plain: "OOD Place of Worship"
    latex: 'OOD Place of Worship'
  test/test-od-region-africa-class-single-unit_residential-task-acc:
    plain: "OOD Single-Unit Residential"
    latex: 'OOD Single-Unit Residential'
  test/test-od-region-africa-class-crop_field-task-acc:
    plain: "OOD Crop Field"
    latex: 'OOD Crop Field'
  test/test-od-region-africa-class-swimming_pool-task-acc:
    plain: "OOD Swimming Pool"
    latex: 'OOD Swimming Pool'
  test/test-od-region-africa-class-multi-unit_residential-task-acc:
    plain: "OOD Multi-Unit Residential"
    latex: 'OOD Multi-Unit Residential'
  test/test-id-region-africa-class-airport-task-acc:
    plain: "ID Airport"
    latex: 'ID Airport'
  test/test-id-region-africa-class-runway-task-acc:
    plain: "ID Runway"
    latex: 'ID Runway'
  test/test-id-region-africa-class-place_of_worship-task-acc:
    plain: "ID Place of Worship"
    latex: 'ID Place of Worship'
  test/test-id-region-africa-class-single-unit_residential-task-acc:
    plain: "ID Single-Unit Residential"
    latex: 'ID Single-Unit Residential'
  test/test-id-region-africa-class-crop_field-task-acc:
    plain: "ID Crop Field"
    latex: 'ID Crop Field'
  test/test-id-region-africa-class-swimming_pool-task-acc:
    plain: "ID Swimming Pool"
    latex: 'ID Swimming Pool'
  test/test-id-region-africa-class-multi-unit_residential-task-acc:
    plain: "ID Multi-Unit Residential"
    latex: 'ID Multi-Unit Residential'

params:
  model.lr_domain_loss_coeff:
    plain: "λ_dom"
    latex: '$\lambda_{\text{dom}}$'
  optim.domain_optimizer_lr_factor:
    plain: "μ_dom"
    latex: '$\mu_{\text{dom}}$'
  trainer.label_smoothing:
    plain: "ε"
    latex: '$\varepsilon$'
  model.learnable_relation_coeff:
    plain: "α_rel"
    latex: '$\alpha_{\text{rel}}$'
  model.consistency_loss_coeff:
    plain: "λ_con"
    latex: '$\lambda_{\text{con}}$'
  model.pred_domain_for_d3g:
    plain: "Domain Prediction"
    latex: "Domain Prediction"
  model.fusion.out_dim:
    plain: "d"
    latex: "$d$"
  model.detach_lr_for_task:
    plain: "⊥_LR→Task"
    latex: '$\bot_{\text{LR}\to\text{Task}}$'
  model.detach_lr_for_consistency:
    plain: "⊥_LR→Con"
    latex: '$\bot_{\text{LR}\to\text{Con}}$'
  model.detach_hr_for_consistency:
    plain: "⊥_HR→Con"
    latex: '$\bot_{\text{HR}\to\text{Con}}$'
  model.fusion.pre_fusion_relu:
    plain: "Pre-ReLU"
    latex: "Pre-ReLU"
  model.landsat_channel_init:
    plain: "Ch-Init"
    latex: "Ch-Init"
  model.decision_rule:
    plain: "Rule"
    latex: "Rule"
    values:
      max:
        plain: "Max"
        latex: '$\mathrm{max}$'
      min:
        plain: "Min"
        latex: '$\mathrm{min}$'
      sum:
        plain: "Sum"
        latex: '$\mathrm{sum}$'
      product:
        plain: "Product"
        latex: '$\mathrm{Product}$'
  model.use_class_prior:
    plain: "Class Prior"
    latex: "Class Prior"
    values:
      false:
        plain: "No Prior"
        latex: 'No Prior'
      true:
        plain: "Class Prior"
        latex: "Class Prior"
  model.train_model:
    plain: "Trained"
    latex: "Trained"
  model.encoder.legendre_polys:
    plain: "L"
    latex: "L"
  model.lr_encoder.legendre_polys:
    plain: "L"
    latex: "L"
  model.encoder.landsat_channel_init:
    plain: "Ch-Init"
    latex: "Ch-Init"
    values:
      zero:
        plain: "zero"
        latex: "zero"
      he:
        plain: "he"
        latex: "he"
  model.landsat_in_channels:
    plain: "In-Ch"
    latex: "In-Ch"
    values:
      3:
        plain: "RGB"
        latex: "RGB"
  data.lr_feature_run_name:
    plain: "LR Source"
    latex: "LR Source"
    values:
      densenet_lr_baseline_no_domain:
        plain: "No Domain"
        latex: "No Domain"
      dinov3_lr_baseline_no_domain:
        plain: "No Domain"
        latex: "No Domain"
      satclip_le_enc_baseline_l_40:
        hidden: true
      satclip_le_enc_baseline_l_40_no_domain:
        plain: "No Domain"
        latex: "No Domain"
  trainer.branch_ablation:
    hidden: true
  data.preprocessed_dir:
    plain: "Norm"
    latex: "Norm"
    values:
      FMoW_LandSat_:
        plain: "N_const"
        latex: '$N_{\text{const}}$'
      FMoW_LandSat_Norm:
        plain: "N_data"
        latex: '$N_{\text{data}}$'
  data.image_norm:
    plain: "Norm"
    latex: "Norm"
  data.lr_crop_km:
    plain: "Extent"
    latex: "Extent"
  spatial:
    plain: "Spatial Encoding"
    latex: "Spatial Encoding"
    values:
      pe_freq:
        plain: "PE_freq"
        latex: '$\text{PE}_{\text{freq}}$'
      pe:
        plain: "PE"
        latex: '$\text{PE}$'
      om_bin:
        plain: "OM_bin"
        latex: '$\text{OM}_{\text{bin}}$'
      om_gauss:
        plain: "OM_gauss"
        latex: '$\text{OM}_{\text{gauss}}$'
      om_bin_pe_freq:
        plain: "OM_bin, PE_freq"
        latex: '$\text{OM}_{\text{bin}}, \text{PE}_{\text{freq}}$'
      om_gauss_pe_freq:
        plain: "OM_gauss, PE_freq"
        latex: '$\text{OM}_{\text{gauss}}, \text{PE}_{\text{freq}}$'
      om_bin_pe:
        plain: "OM_bin, PE"
        latex: '$\text{OM}_{\text{bin}}, \text{PE}$'
      om_gauss_pe:
        plain: "OM_gauss, PE"
        latex: '$\text{OM}_{\text{gauss}}, \text{PE}$'
      pe_freq_hr:
        plain: "PE_freq^HR"
        latex: '$\text{PE}_{\text{freq}}^{\text{HR}}$'
      pe_hr:
        plain: "PE^HR"
        latex: '$\text{PE}^{\text{HR}}$'
      om_gauss_pe_freq_hr:
        plain: "OM_gauss, PE_freq^HR"
        latex: '$\text{OM}_{\text{gauss}}, \text{PE}_{\text{freq}}^{\text{HR}}$'
  trainer.alternating_freeze:
    hidden: true 
  trainer.alternating_freeze_period:
    plain: "T_freeze"
    latex: '$T_{\text{freeze}}$'
  

