models:
  densenet_baseline: "DenseNet"
  densenet_concat: "Concat"
  densenet_film: "FiLM"
  densenet_d3g: "D3G"
  densenet_geoprior: "GeoPrior"
  efficientformer_baseline: "EfficientFormer"
  efficientnet_baseline: "EfficientNet"

params:
  model.lr_domain_loss_coeff:
    plain: "λ_dom"
    latex: '$\lambda_{\text{dom}}$'
  optim.domain_optimizer_lr_factor:
    plain: "μ_dom"
    latex: '$\mu_{\text{dom}}$'
  trainer.label_smoothing:
    plain: "ε"
    latex: '$\varepsilon$'
  model.learnable_relation_coeff:
    plain: "α_rel"
    latex: '$\alpha_{\text{rel}}$'
  model.consistency_loss_coeff:
    plain: "λ_con"
    latex: '$\lambda_{\text{con}}$'
  model.pred_domain_for_d3g:
    plain: "Domain Prediction"
    latex: "Domain Prediction"
  model.fusion.out_dim:
    plain: "d"
    latex: "$d$"
  data.preprocessed_dir:
    plain: "DS-Norm"
    latex: "DS-Norm"
    no_value: true
  data.image_norm:
    plain: "Norm"
    latex: "Norm"
