models:
  densenet_baseline: "DenseNet-121"
  densenet_concat: "Concat"
  densenet_film: "FiLM"
  densenet_d3g: "D3G"
  densenet_geoprior: "GeoPrior"
  densenet_multsim: "MultSim"
  densenet_lr_baseline: "DenseNet LR"
  deit_baseline: "DeiT-Tiny"
  efficientformer_baseline: "EfficientFormerV2-S1"
  efficientnet_baseline: "EffNetV2-B1"
  densenet_satclip_concat: "Concat w. LE"
  densenet_satclip_film: "FiLM w. LE"
  densenet_satclip_d3g: "D3G w. LE"
  densenet_satclip_geoprior: "GeoPrior w. LE"


params:
  model.lr_domain_loss_coeff:
    plain: "λ_dom"
    latex: '$\lambda_{\text{dom}}$'
  optim.domain_optimizer_lr_factor:
    plain: "μ_dom"
    latex: '$\mu_{\text{dom}}$'
  trainer.label_smoothing:
    plain: "ε"
    latex: '$\varepsilon$'
  model.learnable_relation_coeff:
    plain: "α_rel"
    latex: '$\alpha_{\text{rel}}$'
  model.consistency_loss_coeff:
    plain: "λ_con"
    latex: '$\lambda_{\text{con}}$'
  model.pred_domain_for_d3g:
    plain: "Domain Prediction"
    latex: "Domain Prediction"
  model.fusion.out_dim:
    plain: "d"
    latex: "$d$"
  model.detach_lr_for_task:
    plain: "⊥_LR→Task"
    latex: '$\bot_{\text{LR}\to\text{Task}}$'
  model.detach_lr_for_consistency:
    plain: "⊥_LR→Con"
    latex: '$\bot_{\text{LR}\to\text{Con}}$'
  model.detach_hr_for_consistency:
    plain: "⊥_HR→Con"
    latex: '$\bot_{\text{HR}\to\text{Con}}$'
  model.fusion.pre_fusion_relu:
    plain: "Pre-ReLU"
    latex: "Pre-ReLU"
  model.landsat_channel_init:
    plain: "Ch-Init"
    latex: "Ch-Init"
  trainer.branch_ablation:
    hidden: true
  data.preprocessed_dir:
    plain: "Norm"
    latex: "Norm"
    values:
      FMoW_LandSat_:
        plain: "N_const"
        latex: '$N_{\text{const}}$'
      FMoW_LandSat_Norm:
        plain: "N_data"
        latex: '$N_{\text{data}}$'
  data.image_norm:
    plain: "Norm"
    latex: "Norm"
  spatial:
    plain: "Spatial Encoding"
    latex: "Spatial Encoding"
    values:
      pe_freq:
        plain: "PE_freq"
        latex: '$\text{PE}_{\text{freq}}$'
      pe:
        plain: "PE"
        latex: '$\text{PE}$'
      om_bin:
        plain: "OM_bin"
        latex: '$\text{OM}_{\text{bin}}$'
      om_gauss:
        plain: "OM_gauss"
        latex: '$\text{OM}_{\text{gauss}}$'
      om_bin_pe_freq:
        plain: "OM_bin, PE_freq"
        latex: '$\text{OM}_{\text{bin}}, \text{PE}_{\text{freq}}$'
      om_gauss_pe_freq:
        plain: "OM_gauss, PE_freq"
        latex: '$\text{OM}_{\text{gauss}}, \text{PE}_{\text{freq}}$'
      om_bin_pe:
        plain: "OM_bin, PE"
        latex: '$\text{OM}_{\text{bin}}, \text{PE}$'
      om_gauss_pe:
        plain: "OM_gauss, PE"
        latex: '$\text{OM}_{\text{gauss}}, \text{PE}$'
  trainer.alternating_freeze:
    hidden: true 
  trainer.alternating_freeze_period:
    plain: "T_freeze"
    latex: '$T_{\text{freeze}}$'
  

