optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1.0e-4
  weight_decay: 0.0

scheduler: null

domain_optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 0.0

domain_scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 1
  gamma: 0.96

domain_optimizer_lr_factor: 0.1